import { toDateSafe } from './helpers.js';

const parseAmount = (value) => {
    const amount = Number(value);
    return Number.isFinite(amount) ? amount : 0;
};

const isInactive = (item) => (
    item?.deletedAt ||
    item?.silindi ||
    item?.isDeleted ||
    item?.aktif === false ||
    item?.pasif === true
);

const clampDay = (day, year, month) => {
    const lastDay = new Date(year, month + 1, 0).getDate();
    return Math.min(Math.max(Number(day) || 1, 1), lastDay);
};

export const dateToPeriodKey = (date) => {
    if (!date) return '';
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
};

export const dateToDateKey = (date) => {
    if (!date) return '';
    return `${dateToPeriodKey(date)}-${String(date.getDate()).padStart(2, '0')}`;
};

const startOfDay = (date) => {
    if (!date) return null;
    const result = new Date(date);
    result.setHours(0, 0, 0, 0);
    return result;
};

const normalizeText = (value) => String(value || '')
    .toLocaleLowerCase('tr-TR')
    .replace(/\(.*?otomatik.*?\)/giu, ' ')
    .replace(/\botomatik\b/giu, ' ')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/ı/g, 'i')
    .replace(/ğ/g, 'g')
    .replace(/ü/g, 'u')
    .replace(/ş/g, 's')
    .replace(/ö/g, 'o')
    .replace(/ç/g, 'c')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();

const directSubscriptionId = (transaction) => String(
    transaction?.subscriptionId ||
    transaction?.bagliAbonelikId ||
    transaction?.abonelikId ||
    transaction?.autoGeneratedFromId ||
    transaction?.recurringDefinitionId ||
    ''
).trim();

const hasDirectSubscriptionLink = (transaction) => Boolean(directSubscriptionId(transaction));

const isSameSubscriptionByDirectLink = (transaction, subscription) => (
    directSubscriptionId(transaction) === String(subscription?.id || '').trim()
);

const isWithinDays = (transactionDate, dueDate, dayWindow) => {
    if (!transactionDate || !dueDate) return false;
    const oneDay = 24 * 60 * 60 * 1000;
    const diff = Math.abs(startOfDay(transactionDate) - startOfDay(dueDate));
    return diff <= dayWindow * oneDay;
};

const accountMatches = (transaction, subscription) => {
    const subscriptionAccountId = String(subscription?.hesapId || subscription?.accountId || '').trim();
    if (!subscriptionAccountId) return true;
    return String(transaction?.hesapId || transaction?.accountId || '').trim() === subscriptionAccountId;
};

const amountMatches = (transaction, expectedAmount) => (
    Math.abs(Math.abs(parseAmount(transaction?.tutar)) - Math.abs(parseAmount(expectedAmount))) <= 1
);

const descriptionMatches = (transaction, subscription) => {
    const subscriptionName = normalizeText(subscription?.ad || subscription?.baslik || subscription?.name);
    if (!subscriptionName) return false;
    const description = normalizeText([
        transaction?.aciklama,
        transaction?.baslik,
        transaction?.title,
        transaction?.kategori,
    ].filter(Boolean).join(' '));
    if (!description) return false;
    return description === subscriptionName ||
        description.includes(subscriptionName) ||
        subscriptionName.includes(description);
};

const isSubscriptionPaymentCandidate = (transaction) => {
    if (!transaction) return false;
    if (transaction.islemTipi && transaction.islemTipi !== 'gider') return false;
    return parseAmount(transaction.tutar) !== 0;
};

const transactionMatchesSubscriptionOccurrence = (transaction, occurrence) => {
    if (!isSubscriptionPaymentCandidate(transaction)) return false;
    const transactionDate = toDateSafe(transaction.tarih);
    if (!transactionDate) return false;

    if (hasDirectSubscriptionLink(transaction)) {
        return isSameSubscriptionByDirectLink(transaction, occurrence.subscription) &&
            dateToPeriodKey(transactionDate) === occurrence.periodKey;
    }

    return accountMatches(transaction, occurrence.subscription) &&
        isWithinDays(transactionDate, occurrence.dueDate, 3) &&
        amountMatches(transaction, occurrence.expectedAmount) &&
        descriptionMatches(transaction, occurrence.subscription);
};

const getMatchPriority = (transaction) => (hasDirectSubscriptionLink(transaction) ? 0 : 1);

const sortMatchCandidates = (a, b) => {
    const priorityDiff = getMatchPriority(a.transaction) - getMatchPriority(b.transaction);
    if (priorityDiff !== 0) return priorityDiff;
    const dateA = toDateSafe(a.transaction.tarih)?.getTime() || 0;
    const dateB = toDateSafe(b.transaction.tarih)?.getTime() || 0;
    return dateA - dateB;
};

export const buildSubscriptionOccurrences = ({
    subscriptions = [],
    transactions = [],
    year,
    month,
    today = new Date(),
} = {}) => {
    if (!Number.isInteger(year) || !Number.isInteger(month)) return [];

    const todayStart = startOfDay(today);
    const usedTransactionIds = new Set();
    const occurrences = (subscriptions || [])
        .filter((subscription) => !isInactive(subscription))
        .map((subscription) => {
            const day = Number(subscription.gun || subscription.odemeGunu || 0);
            if (!Number.isFinite(day) || day <= 0) return null;
            const dueDate = new Date(year, month, clampDay(day, year, month));
            const periodKey = dateToPeriodKey(dueDate);
            return {
                id: `subscription-${subscription.id}-${periodKey}`,
                subscriptionId: subscription.id,
                dueDate,
                dateKey: dateToDateKey(dueDate),
                periodKey,
                expectedAmount: parseAmount(subscription.tutar),
                status: 'upcoming',
                matchedTransactionId: null,
                subscription,
            };
        })
        .filter(Boolean);

    occurrences.forEach((occurrence) => {
        const candidates = (transactions || [])
            .filter((transaction) => {
                const id = String(transaction?.id || '').trim();
                if (id && usedTransactionIds.has(id)) return false;
                return transactionMatchesSubscriptionOccurrence(transaction, occurrence);
            })
            .map((transaction) => ({ transaction }))
            .sort(sortMatchCandidates);

        const match = candidates[0]?.transaction;
        if (match) {
            const id = String(match.id || '').trim();
            if (id) usedTransactionIds.add(id);
            occurrence.status = 'paid';
            occurrence.matchedTransactionId = id || null;
            occurrence.matchedTransaction = match;
            return;
        }

        if (startOfDay(occurrence.dueDate) < todayStart) {
            occurrence.status = 'overdue';
        }
    });

    return occurrences;
};
